name:                applied
version:             0.1.0.0
github:              "githubuser/applied"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/applied#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.0.1 && < 0.7
- mtl >= 2.2 && <= 2.3
- logict >= 0.6 && <= 0.6.1
- monad-loops >= 0.4 && <= 0.4.3
- random >= 1.0 && <= 1.1
- conduit >= 1.3.1 && <= 1.3.2
- conduit-extra >= 1.3.0 && <= 1.3.1
- bytestring >= 0.10.1 && <= 0.11
- network >= 2.8.0 && <= 2.8.1

library:
  source-dirs: src

executables:
  applied-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - applied

tests:
  applied-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - applied
